---
title: "Untitled"
author: "Riaz Gillani"
date: "2023-08-01"
output: html_document
---

```{r}

library(MASS)
library(tidyverse)
library(useful)
library(here)
library(dplyr)
library(ggplot2)
library(RColorBrewer)
library(ggrepel)
library(VennDiagram)
library(stringr)
library(scales)
library(grid)
library(exact2x2)
library(readr)
library(biomaRt)
library(sqldf)
library(gridExtra)
library(ggbeeswarm)
library(caret)
library(vcfR)
library(bedr)
library(PedSV)
library(parallel)
library(argparse)
library(qqman)
library(metafor)
library(rCNV2)
library(ggpubr)
library(ggbeeswarm)
library(quest)
PedSV::load.constants("all")

```

#neuroblastoma noncoding CWAS - enumeration of categories
```{r}
CWAS_categories_neuroblastoma_noncoding <- read_tsv(here::here("data","CWAS_rare_categories_neuroblastoma_noncoding_10_2_23.txt"))

neuroblastoma_noncoding_CWAS_sv_type <- CWAS_categories_neuroblastoma_noncoding %>% filter(!is.na(sv_type)) %>% distinct(sv_type) %>% unlist() %>% unname()

neuroblastoma_noncoding_CWAS_frequency <- CWAS_categories_neuroblastoma_noncoding %>% filter(!is.na(frequency)) %>% distinct(frequency) %>% unlist() %>% unname()

neuroblastoma_noncoding_CWAS_functional_intersection <- CWAS_categories_neuroblastoma_noncoding %>% filter(!is.na(functional_intersection)) %>% distinct(functional_intersection) %>% unlist() %>% unname()

neuroblastoma_noncoding_CWAS_functional_category <- CWAS_categories_neuroblastoma_noncoding %>% filter(!is.na(functional_category)) %>% distinct(functional_category) %>% unlist() %>% unname()

neuroblastoma_noncoding_CWAS_genic_relationship <- CWAS_categories_neuroblastoma_noncoding %>% filter(!is.na(genic_relationship)) %>% distinct(genic_relationship) %>% unlist() %>% unname()

neuroblastoma_noncoding_CWAS_constraint <- CWAS_categories_neuroblastoma_noncoding %>% filter(!is.na(constraint)) %>% distinct(constraint) %>% unlist() %>% unname()

neuroblastoma_noncoding_CWAS_expression <- CWAS_categories_neuroblastoma_noncoding %>% filter(!is.na(expression)) %>% distinct(expression) %>% unlist() %>% unname()

neuroblastoma_noncoding_CWAS_gene_group <- CWAS_categories_neuroblastoma_noncoding %>% filter(!is.na(gene_group)) %>% distinct(gene_group) %>% unlist() %>% unname()

neuroblastoma_noncoding_CWAS_enumerated_categories <- tibble(sv_type = NA, frequency = NA, functional_intersection = NA, functional_category = NA, genic_relationship = NA, constraint = NA, expression = NA, gene_group = NA)

count <- 0

for(sv_type in neuroblastoma_noncoding_CWAS_sv_type){
  for(frequency in neuroblastoma_noncoding_CWAS_frequency){
    for(functional_intersection in neuroblastoma_noncoding_CWAS_functional_intersection){
      for(functional_category in neuroblastoma_noncoding_CWAS_functional_category){
        for(genic_relationship in neuroblastoma_noncoding_CWAS_genic_relationship){
          for(constraint in neuroblastoma_noncoding_CWAS_constraint){
            for(expression in neuroblastoma_noncoding_CWAS_expression){
              for(gene_group in neuroblastoma_noncoding_CWAS_gene_group){
              
              neuroblastoma_noncoding_CWAS_enumerated_categories <- add_row(neuroblastoma_noncoding_CWAS_enumerated_categories, frequency = frequency, sv_type = sv_type, functional_intersection = functional_intersection, functional_category = functional_category, genic_relationship = genic_relationship, constraint = constraint, expression = expression, gene_group = gene_group)
              
              count = count + 1
              print(count)
              
              }
            }  
          }
        }
      }
    }
  }
}

neuroblastoma_noncoding_CWAS_enumerated_categories <- neuroblastoma_noncoding_CWAS_enumerated_categories[-1,]

neuroblastoma_noncoding_CWAS_enumerated_categories_unique <- neuroblastoma_noncoding_CWAS_enumerated_categories %>% distinct()

neuroblastoma_noncoding_CWAS_enumerated_categories_unique <- neuroblastoma_noncoding_CWAS_enumerated_categories_unique %>% mutate(unique_category_id = str_c(sv_type,".",frequency,".",functional_intersection,".",functional_category,".",genic_relationship,".",constraint,".",expression,".",gene_group))

write_tsv(neuroblastoma_noncoding_CWAS_enumerated_categories_unique,here::here("data","neuroblastoma_noncoding_CWAS_enumerated_categories_unique_10_23_23.txt"))
```

#ewing noncoding CWAS - enumeration of categories
```{r}
CWAS_categories_ewing_noncoding <- read_tsv(here::here("data","CWAS_rare_categories_ewing_noncoding_10_2_23.txt"))

ewing_noncoding_CWAS_sv_type <- CWAS_categories_ewing_noncoding %>% filter(!is.na(sv_type)) %>% distinct(sv_type) %>% unlist() %>% unname()

ewing_noncoding_CWAS_frequency <- CWAS_categories_ewing_noncoding %>% filter(!is.na(frequency)) %>% distinct(frequency) %>% unlist() %>% unname()

ewing_noncoding_CWAS_functional_intersection <- CWAS_categories_ewing_noncoding %>% filter(!is.na(functional_intersection)) %>% distinct(functional_intersection) %>% unlist() %>% unname()

ewing_noncoding_CWAS_functional_category <- CWAS_categories_ewing_noncoding %>% filter(!is.na(functional_category)) %>% distinct(functional_category) %>% unlist() %>% unname()

ewing_noncoding_CWAS_genic_relationship <- CWAS_categories_ewing_noncoding %>% filter(!is.na(genic_relationship)) %>% distinct(genic_relationship) %>% unlist() %>% unname()

ewing_noncoding_CWAS_constraint <- CWAS_categories_ewing_noncoding %>% filter(!is.na(constraint)) %>% distinct(constraint) %>% unlist() %>% unname()

ewing_noncoding_CWAS_expression <- CWAS_categories_ewing_noncoding %>% filter(!is.na(expression)) %>% distinct(expression) %>% unlist() %>% unname()

ewing_noncoding_CWAS_gene_group <- CWAS_categories_ewing_noncoding %>% filter(!is.na(gene_group)) %>% distinct(gene_group) %>% unlist() %>% unname()

ewing_noncoding_CWAS_enumerated_categories <- tibble(sv_type = NA, frequency = NA, functional_intersection = NA, functional_category = NA, genic_relationship = NA, constraint = NA, expression = NA, gene_group = NA)

count <- 0

for(sv_type in ewing_noncoding_CWAS_sv_type){
  for(frequency in ewing_noncoding_CWAS_frequency){
    for(functional_intersection in ewing_noncoding_CWAS_functional_intersection){
      for(functional_category in ewing_noncoding_CWAS_functional_category){
        for(genic_relationship in ewing_noncoding_CWAS_genic_relationship){
          for(constraint in ewing_noncoding_CWAS_constraint){
            for(expression in ewing_noncoding_CWAS_expression){
              for(gene_group in ewing_noncoding_CWAS_gene_group){
              
              ewing_noncoding_CWAS_enumerated_categories <- add_row(ewing_noncoding_CWAS_enumerated_categories, frequency = frequency, sv_type = sv_type, functional_intersection = functional_intersection, functional_category = functional_category, genic_relationship = genic_relationship, constraint = constraint, expression = expression, gene_group = gene_group)
              
              count = count + 1
              print(count)
              
              }
            }  
          }
        }
      }
    }
  }
}

ewing_noncoding_CWAS_enumerated_categories <- ewing_noncoding_CWAS_enumerated_categories[-1,]

ewing_noncoding_CWAS_enumerated_categories_unique <- ewing_noncoding_CWAS_enumerated_categories %>% distinct()

ewing_noncoding_CWAS_enumerated_categories_unique <- ewing_noncoding_CWAS_enumerated_categories_unique %>% mutate(unique_category_id = str_c(sv_type,".",frequency,".",functional_intersection,".",functional_category,".",genic_relationship,".",constraint,".",expression,".",gene_group))

write_tsv(ewing_noncoding_CWAS_enumerated_categories_unique,here::here("data","ewing_noncoding_CWAS_enumerated_categories_unique_10_23_23.txt"))
```

#Parallelizing SV assignment to categories by creating shards of categories
```{r}

#Neuroblastoma all noncoding CWAS

neuroblastoma_all_noncoding_CWAS_enumerated_categories_unique <- read_tsv(here::here("data","neuroblastoma_noncoding_CWAS_enumerated_categories_unique_10_23_23.txt"))

shards_of_neuroblastoma_all_noncoding_CWAS_enumerated_categories_unique <- split(neuroblastoma_all_noncoding_CWAS_enumerated_categories_unique,ceiling(seq_along(neuroblastoma_all_noncoding_CWAS_enumerated_categories_unique$unique_category_id)/1000))

count <- 0

for(index in 1:length(shards_of_neuroblastoma_all_noncoding_CWAS_enumerated_categories_unique)){

write_tsv(shards_of_neuroblastoma_all_noncoding_CWAS_enumerated_categories_unique[[index]] %>% as_tibble(),here::here("data/neuroblastoma_all_noncoding_CWAS_category_shards_SV_ASSIGNMENT_10_23_23",str_c("neuroblastoma_all_noncoding_shard_",index,".txt")))
  
count <- count + 1  

print(count)

}

#ewing all noncoding CWAS

ewing_all_noncoding_CWAS_enumerated_categories_unique <- read_tsv(here::here("data","ewing_noncoding_CWAS_enumerated_categories_unique_10_23_23.txt"))

shards_of_ewing_all_noncoding_CWAS_enumerated_categories_unique <- split(ewing_all_noncoding_CWAS_enumerated_categories_unique,ceiling(seq_along(ewing_all_noncoding_CWAS_enumerated_categories_unique$unique_category_id)/1000))

count <- 0

for(index in 1:length(shards_of_ewing_all_noncoding_CWAS_enumerated_categories_unique)){

write_tsv(shards_of_ewing_all_noncoding_CWAS_enumerated_categories_unique[[index]] %>% as_tibble(),here::here("data/ewing_all_noncoding_CWAS_category_shards_SV_ASSIGNMENT_10_23_23",str_c("ewing_all_noncoding_shard_",index,".txt")))
  
count <- count + 1  

print(count)

}


```

#Parallelizing burden testing by creating shards of categories (using output from SV assignment workflow)
```{r}

#Neuroblastoma discovery noncoding CWAS

neuroblastoma_discovery_SVs_in_each_category_list_combined <- read_tsv(here::here("data","neuroblastoma_discovery_noncoding_SVs_in_each_category_list_combined_BURDEN_TESTING_4_11_24.txt"), col_names = c("SV","chrom","start","end","category"))

write_tsv(neuroblastoma_discovery_SVs_in_each_category_list_combined,here::here("data","neuroblastoma_discovery_noncoding_SVs_in_each_category_list_combined_BURDEN_TESTING_with_col_names_4_11_24.txt"))

neuroblastoma_discovery_unique_list_of_categories <- unique(neuroblastoma_discovery_SVs_in_each_category_list_combined$category)

neuroblastoma_discovery_unique_list_of_categories_list <- split(neuroblastoma_discovery_unique_list_of_categories,ceiling(seq_along(neuroblastoma_discovery_unique_list_of_categories)/100))

count <- 0

for(index in 1:length(neuroblastoma_discovery_unique_list_of_categories_list)){

write_tsv(neuroblastoma_discovery_unique_list_of_categories_list[[index]] %>% as_tibble(),here::here("data/neuroblastoma_discovery_noncoding_CWAS_category_shards_BURDEN_TESTING_4_11_24",str_c("neuroblastoma_discovery_noncoding_shard_",index,".txt")), col_names = FALSE)
  
count <- count + 1  

print(count)

}

#Neuroblastoma trio noncoding CWAS

neuroblastoma_trio_SVs_in_each_category_list_combined <- read_tsv(here::here("data","neuroblastoma_trio_noncoding_SVs_in_each_category_list_combined_BURDEN_TESTING_4_11_24.txt"), col_names = c("SV","chrom","start","end","category"))

write_tsv(neuroblastoma_trio_SVs_in_each_category_list_combined,here::here("data","neuroblastoma_trio_noncoding_SVs_in_each_category_list_combined_BURDEN_TESTING_with_col_names_4_11_24.txt"))

neuroblastoma_trio_unique_list_of_categories <- unique(neuroblastoma_trio_SVs_in_each_category_list_combined$category)

neuroblastoma_trio_unique_list_of_categories_list <- split(neuroblastoma_trio_unique_list_of_categories,ceiling(seq_along(neuroblastoma_trio_unique_list_of_categories)/100))

count <- 0

for(index in 1:length(neuroblastoma_trio_unique_list_of_categories_list)){

write_tsv(neuroblastoma_trio_unique_list_of_categories_list[[index]] %>% as_tibble(),here::here("data/neuroblastoma_trio_noncoding_CWAS_category_shards_BURDEN_TESTING_4_11_24",str_c("neuroblastoma_trio_noncoding_shard_",index,".txt")), col_names = FALSE)
  
count <- count + 1  

print(count)

}

#ewing discovery noncoding CWAS

ewing_discovery_SVs_in_each_category_list_combined <- read_tsv(here::here("data","ewing_discovery_noncoding_SVs_in_each_category_list_combined_BURDEN_TESTING_4_11_24.txt"), col_names = c("SV","chrom","start","end","category"))

write_tsv(ewing_discovery_SVs_in_each_category_list_combined,here::here("data","ewing_discovery_noncoding_SVs_in_each_category_list_combined_BURDEN_TESTING_with_col_names_4_11_24.txt"))

ewing_discovery_unique_list_of_categories <- unique(ewing_discovery_SVs_in_each_category_list_combined$category)

ewing_discovery_unique_list_of_categories_list <- split(ewing_discovery_unique_list_of_categories,ceiling(seq_along(ewing_discovery_unique_list_of_categories)/100))

count <- 0

for(index in 1:length(ewing_discovery_unique_list_of_categories_list)){

write_tsv(ewing_discovery_unique_list_of_categories_list[[index]] %>% as_tibble(),here::here("data/ewing_discovery_noncoding_CWAS_category_shards_BURDEN_TESTING_4_11_24",str_c("ewing_discovery_noncoding_shard_",index,".txt")), col_names = FALSE)
  
count <- count + 1  

print(count)

}

#ewing trio noncoding CWAS

ewing_trio_SVs_in_each_category_list_combined <- read_tsv(here::here("data","ewing_trio_noncoding_SVs_in_each_category_list_combined_BURDEN_TESTING_4_11_24.txt"), col_names = c("SV","chrom","start","end","category"))

write_tsv(ewing_trio_SVs_in_each_category_list_combined,here::here("data","ewing_trio_noncoding_SVs_in_each_category_list_combined_BURDEN_TESTING_with_col_names_4_11_24.txt"))

ewing_trio_unique_list_of_categories <- unique(ewing_trio_SVs_in_each_category_list_combined$category)

ewing_trio_unique_list_of_categories_list <- split(ewing_trio_unique_list_of_categories,ceiling(seq_along(ewing_trio_unique_list_of_categories)/100))

count <- 0

for(index in 1:length(ewing_trio_unique_list_of_categories_list)){

write_tsv(ewing_trio_unique_list_of_categories_list[[index]] %>% as_tibble(),here::here("data/ewing_trio_noncoding_CWAS_category_shards_BURDEN_TESTING_4_11_24",str_c("ewing_trio_noncoding_shard_",index,".txt")), col_names = FALSE)
  
count <- count + 1  

print(count)

}

#Neuroblastoma all noncoding CWAS

neuroblastoma_all_SVs_in_each_category_list_combined <- read_tsv(here::here("data","neuroblastoma_all_noncoding_SVs_in_each_category_list_combined_BURDEN_TESTING_4_11_24.txt"), col_names = c("SV","chrom","start","end","category"))

write_tsv(neuroblastoma_all_SVs_in_each_category_list_combined,here::here("data","neuroblastoma_all_noncoding_SVs_in_each_category_list_combined_BURDEN_TESTING_with_col_names_4_11_24.txt"))

neuroblastoma_all_unique_list_of_categories <- unique(neuroblastoma_all_SVs_in_each_category_list_combined$category)

neuroblastoma_all_unique_list_of_categories_list <- split(neuroblastoma_all_unique_list_of_categories,ceiling(seq_along(neuroblastoma_all_unique_list_of_categories)/100))

count <- 0

for(index in 1:length(neuroblastoma_all_unique_list_of_categories_list)){

write_tsv(neuroblastoma_all_unique_list_of_categories_list[[index]] %>% as_tibble(),here::here("data/neuroblastoma_all_noncoding_CWAS_category_shards_BURDEN_TESTING_4_11_24",str_c("neuroblastoma_all_noncoding_shard_",index,".txt")), col_names = FALSE)
  
count <- count + 1  

print(count)

}

#ewing all noncoding CWAS

ewing_all_SVs_in_each_category_list_combined <- read_tsv(here::here("data","ewing_all_noncoding_SVs_in_each_category_list_combined_BURDEN_TESTING_4_11_24.txt"), col_names = c("SV","chrom","start","end","category"))

write_tsv(ewing_all_SVs_in_each_category_list_combined,here::here("data","ewing_all_noncoding_SVs_in_each_category_list_combined_BURDEN_TESTING_with_col_names_4_11_24.txt"))

ewing_all_unique_list_of_categories <- unique(ewing_all_SVs_in_each_category_list_combined$category)

ewing_all_unique_list_of_categories_list <- split(ewing_all_unique_list_of_categories,ceiling(seq_along(ewing_all_unique_list_of_categories)/100))

count <- 0

for(index in 1:length(ewing_all_unique_list_of_categories_list)){

write_tsv(ewing_all_unique_list_of_categories_list[[index]] %>% as_tibble(),here::here("data/ewing_all_noncoding_CWAS_category_shards_BURDEN_TESTING_4_11_24",str_c("ewing_all_noncoding_shard_",index,".txt")), col_names = FALSE)
  
count <- count + 1  

print(count)

}

```
